server:
  port: 8088

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/shopapp?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ${MYSQL_ROOT_PASSWORD:Abc123456789@}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  messages:
    basename: i18n/messages
    encoding: UTF-8
    default-locale: en

  flyway:
    locations: classpath:/db/migration,classpath:/dev/db/migration
    baseline-on-migrate: true
    baseline-version: 0

  data:
    redis:
      use-redis-cache: false
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  kafka:
    client:
      dns:
        lookup: use_dns_cache
    bootstrap-servers: ${KAFKA_BROKER_SERVER:localhost}:${KAFKA_BROKER_PORT:9092}
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        "[spring.json.type.mapping]": category:com.project.shopapp.models.Category
    consumer:
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer

  security:
    oauth2:
      client:
        registration:
          facebook:
            clientId: YOUR_FACEBOOK_APP_ID
            clientSecret: YOUR_FACEBOOK_APP_SECRET
            scope:
              - email
              - public_profile

api:
  prefix: /api/v1

jwt:
  expiration: 2592000
  expiration-refresh-token: 5184000
  secretKey: TaqlmGv1iEDMRiFp/pHuID1+T84IABfuA0xXh4GhiUI=

logging:
  level:
    org:
      springframework.security: DEBUG

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
  show-actuator: true

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      base-path: /api/v1/actuator
      exposure:
        include: "health, info"
